# -*- coding: utf-8 -*-
"""PNEUMOAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2MBtZvl_dw_A6SNasLbr2X3VpFHiTwd
"""

img = cv2.imread(img_path)

img = cv2.resize(img, (224,224))

heatmap = cv2.resize(heatmap, (224,224))

heatmap = np.uint8(255 * heatmap)

heatmap = cv2.applyColorMap(
    heatmap,
    cv2.COLORMAP_JET
)

superimposed_img = heatmap * 0.4 + img

cv2.imwrite(
    'gradcam_result.jpg',
    superimposed_img
)

plt.figure(figsize=(8,8))

plt.imshow(cv2.cvtColor(
    np.uint8(superimposed_img),
    cv2.COLOR_BGR2RGB
))

plt.axis('off')

plt.show()

plt.matshow(heatmap)
plt.colorbar()
plt.show()

with tf.GradientTape() as tape:

    conv_outputs, predictions = grad_model(img_array)

    loss = predictions[:, 0]

grads = tape.gradient(loss, conv_outputs)

pooled_grads = tf.reduce_mean(grads, axis=(0,1,2))

conv_outputs = conv_outputs[0]

heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]

heatmap = tf.squeeze(heatmap)

heatmap = np.maximum(heatmap, 0)

heatmap /= np.max(heatmap)

grad_model = tf.keras.models.Model(

    [model.inputs],

    [last_conv_layer.output, model.output]

)

last_conv_layer = model.get_layer('conv5_block16_concat')

prediction = model.predict(img_array)

print("Prediction:", prediction)

img_path = '/content/Pneumonia.jpeg'

img = tf.keras.preprocessing.image.load_img(
    img_path,
    target_size=(224,224)
)

img_array = tf.keras.preprocessing.image.img_to_array(img)

img_array = np.expand_dims(img_array, axis=0)

img_array = img_array / 255.0

import tensorflow as tf
import numpy as np
import cv2
import matplotlib.pyplot as plt

from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

img = image.load_img(
    '/content/Pneumonia.jpeg',
    target_size=(224,224)
)

plt.imshow(img)
plt.axis('off')

img_array = image.img_to_array(img)/255.0

img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)

print(prediction)

print(classification_report(

    val_data.classes,

    pred

))

cm = confusion_matrix(

    val_data.classes,

    pred

)

print(cm)

pred = model.predict(val_data)

pred = (pred > 0.5).astype(int)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import numpy as np

model.save("pneumonia_model.h5")

history = model.fit(

    train_data,

    validation_data=val_data,

    epochs=20,

    callbacks=[early_stop]

)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(

    monitor='val_loss',

    patience=3,

    restore_best_weights=True

)

model.compile(

    optimizer='adam',

    loss='binary_crossentropy',

    metrics=['accuracy']

)

x = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)

x = tf.keras.layers.Dense(128, activation='relu')(x)

x = tf.keras.layers.Dropout(0.5)(x)

output = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model = tf.keras.Model(
    inputs=base_model.input,
    outputs=output
)

base_model = tf.keras.applications.DenseNet121(

    include_top=False,

    weights='imagenet',

    input_shape=(224,224,3)

)

base_model.trainable = False

train_data = train_generator.flow_from_directory(

    path + '/chest_xray/train',

    target_size=(224,224),

    batch_size=32,

    class_mode='binary',

    subset='training'

)

val_data = train_generator.flow_from_directory(

    path + '/chest_xray/train',

    target_size=(224,224),

    batch_size=32,

    class_mode='binary',

    subset='validation'

)

import kagglehub

path = kagglehub.dataset_download(
    "paultimothymooney/chest-xray-pneumonia"
)

print(path)

train_data = train_generator.flow_from_directory(

    path + '/chest_xray/train',

    target_size=(224,224),

    batch_size=32,

    class_mode='binary',

    subset='training'

)

val_data = train_generator.flow_from_directory(

    path + '/chest_xray/train',

    target_size=(224,224),

    batch_size=32,

    class_mode='binary',

    subset='validation'

)

train_generator = ImageDataGenerator(

    rescale=1./255,

    rotation_range=20,

    zoom_range=0.2,

    width_shift_range=0.1,

    height_shift_range=0.1,

    horizontal_flip=True,

    validation_split=0.2

)

import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator

history = model.fit(

    train_data,

    validation_data=val_data,

    epochs=20,

    callbacks=[early_stop]

)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(

    monitor='val_loss',

    patience=3,

    restore_best_weights=True

)

model.compile(

    optimizer='adam',

    loss='binary_crossentropy',

    metrics=['accuracy']

)

x = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)

x = tf.keras.layers.Dense(128, activation='relu')(x)

x = tf.keras.layers.Dropout(0.5)(x)

output = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model = tf.keras.Model(
    inputs=base_model.input,
    outputs=output
)

base_model = tf.keras.applications.DenseNet121(

    include_top=False,

    weights='imagenet',

    input_shape=(224,224,3)

)

base_model.trainable = False

val_data = val_generator.flow_from_directory(

    path + '/chest_xray/val',

    target_size=(224,224),

    batch_size=32,

    class_mode='binary'

)

val_generator = ImageDataGenerator(
    rescale=1./255
)

import tensorflow as tf

import kagglehub

path = kagglehub.dataset_download(
    "paultimothymooney/chest-xray-pneumonia"
)

print(path)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(

    monitor='val_loss',

    patience=3,

    restore_best_weights=True

)

model.compile(

    optimizer='adam',

    loss='binary_crossentropy',

    metrics=['accuracy']

)

x = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)

x = tf.keras.layers.Dense(128, activation='relu')(x)

x = tf.keras.layers.Dropout(0.5)(x)

output = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model = tf.keras.Model(
    inputs=base_model.input,
    outputs=output
)

base_model = tf.keras.applications.DenseNet121(

    include_top=False,

    weights='imagenet',

    input_shape=(224,224,3)

)

base_model.trainable = False

import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(

    monitor='val_loss',

    patience=3,

    restore_best_weights=True

)

model.compile(

    optimizer='adam',

    loss='binary_crossentropy',

    metrics=['accuracy']

)

x = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)

x = tf.keras.layers.Dense(128, activation='relu')(x)

x = tf.keras.layers.Dropout(0.5)(x)

output = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model = tf.keras.Model(
    inputs=base_model.input,
    outputs=output
)

base_model = tf.keras.applications.DenseNet121(

    include_top=False,

    weights='imagenet',

    input_shape=(224,224,3)

)

base_model.trainable = False

train_data = train_generator.flow_from_directory(

    path + '/chest_xray/train',

    target_size=(224,224),

    batch_size=32,

    class_mode='binary'

)

val_data = val_generator.flow_from_directory(

    path + '/chest_xray/val',

    target_size=(224,224),

    batch_size=32,

    class_mode='binary'

)

train_generator = ImageDataGenerator(

    rescale=1./255,

    rotation_range=20,

    zoom_range=0.2,

    width_shift_range=0.1,

    height_shift_range=0.1,

    horizontal_flip=True

)

val_generator = ImageDataGenerator(
    rescale=1./255
)

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

history = model.fit(

    train_data,

    validation_data=val_data,

    epochs=10

)

model.compile(

    optimizer='adam',

    loss='binary_crossentropy',

    metrics=['accuracy']

)

x = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)

x = tf.keras.layers.Dense(128, activation='relu')(x)

x = tf.keras.layers.Dropout(0.3)(x)

output = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model = tf.keras.Model(
    inputs=base_model.input,
    outputs=output
)

base_model = tf.keras.applications.DenseNet121(

    include_top=False,

    weights='imagenet',

    input_shape=(224,224,3)

)

base_model.trainable = False

train_generator = ImageDataGenerator(
    rescale=1./255
)

train_data = train_generator.flow_from_directory(

    path + '/chest_xray/train',

    target_size=(224,224),

    batch_size=32,

    class_mode='binary'

)

val_data = train_generator.flow_from_directory(

    path + '/chest_xray/val',

    target_size=(224,224),

    batch_size=32,

    class_mode='binary'

)

import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_generator = ImageDataGenerator(
    rescale=1./255
)

train_data = train_generator.flow_from_directory(

    path + '/chest_xray/train',

    target_size=(224,224),

    batch_size=32,

    class_mode='binary'

)

val_data = train_generator.flow_from_directory(

    path + '/chest_xray/val',

    target_size=(224,224),

    batch_size=32,

    class_mode='binary'

)

import os

os.listdir(path)

import kagglehub

path = kagglehub.dataset_download(
    "paultimothymooney/chest-xray-pneumonia"
)

print("Dataset downloaded to:", path)

!pip install kagglehub

!mkdir -p ~/.kaggle

!echo "KGAT_3f7c1db30bd47661b19a3e27cfdd9ee6" > ~/.kaggle/access_token

!chmod 600 ~/.kaggle/access_token